project:
  type: website
  output-dir: docs


website:
  title: "Intro to LLMs"
  favicon: img/surf.png
  navbar:
    logo: img/surf.png
    left:
      - file: index.qmd
        text: Home
      - file: session1.qmd
        text: "Session 1"
      - file: session2.qmd
        text: "Session 2"

    #right:
    #  - icon: bar-chart-fill
    #    href: whatever
  
  page-footer: 
    right: |
      ![Logo image](/img/icmat.png){width=50%}
    left: |
      ![Logo image](/img/cunef.png){width=50%}


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



